ALTER TABLE `accounts` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `accounts` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `accounts` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `installments` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `installments` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `installments` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `ledger_entries` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `ledger_entries` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `ledger_entries` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `transactions` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `transactions` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `transactions` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `refresh_tokens` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `refresh_tokens` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `refresh_tokens` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `sessions` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `sessions` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `sessions` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `users` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `users` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `users` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `companies` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `companies` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `companies` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `company_users` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `company_users` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `company_users` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `invites` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `invites` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `invites` RENAME COLUMN `deletedAt` TO `deleted_at`;--> statement-breakpoint
ALTER TABLE `projects` RENAME COLUMN `createdAt` TO `created_at`;--> statement-breakpoint
ALTER TABLE `projects` RENAME COLUMN `updatedAt` TO `updated_at`;--> statement-breakpoint
ALTER TABLE `projects` RENAME COLUMN `deletedAt` TO `deleted_at`;