export const routeGroups = {
  common: [
    "BAD_REQUEST",
    "INTERNAL_ERROR",
    "RATE_LIMIT_EXCEEDED",
    "UNSUPPORTED_MEDIA_TYPE",
  ],
  form: ["INVALID_JSON", "VALIDATION_ERROR"],
  auth: ["INVALID_TOKEN", "TOKEN_EXPIRED", "UNAUTHORIZED"],
  user: ["USER_NOT_FOUND", "EMAIL_ALREADY_EXISTS"],
  permission: ["FORBIDDEN"],
  company: ["COMPANY_NOT_FOUND"],
  member: ["MEMBER_NOT_FOUND"],
  invitation: [
    "INVITATION_EXPIRED",
    "INVITATION_NOT_FOUND",
    "INVITATION_ALREADY_ACCEPTED",
    "INVITATION_REVOKED",
    "INVITATION_EMAIL_MISMATCH",
  ],
  verification: [
    "EMAIL_ALREADY_VERIFIED",
    "VERIFICATION_EMAIL_NOT_FOUND",
    "VERIFICATION_NOT_FOUND",
    "VERIFICATION_EXPIRED",
    "EMAIL_VERIFICATION_COOLDOWN",
  ],
} as const;
